shell /usr/bin/fish

# ===============================
# General
# ===============================
font_family      JetBrains Mono
font_size        12.0
bold_brightens_ansi_colors yes
cursor_shape     block
cursor_blink     yes
scrollback_lines 10000
window_padding_width 10
# ===============================
# Colors (OLED)
# ===============================
background        #000000
foreground        #d4d4d4
cursor            #f5c2e7
selection_foreground #000000
selection_background #89ddff

# ===============================
# ANSI Colors
# ===============================
color0  #000000
color1  #ff5370
color2  #89ddff
color3  #f9e2af
color4  #4ade80
color5  #f5c2e7
color6  #c792ea
color7  #cdd6f4

color8  #585b70
color9  #ff5370
color10 #89ddff
color11 #f9e2af
color12 #4ade80
color13 #f5c2e7
color14 #c792ea
color15 #ffffff
