shell /usr/bin/fish

# ===============================
# General
# ===============================
font_family      JetBrains Mono
font_size        12.0
bold_brightens_ansi_colors yes
cursor_shape     block
cursor_blink     yes
scrollback_lines 10000
window_padding_width 10
# ===============================
# Colors
# ===============================
background        #0f111a
foreground        #8f93a2
cursor            #f5c2e7
selection_foreground #1e1e2e
selection_background #89ddff

# ===============================
# ANSI Colors
# ===============================
color0  #0f111a
color1  #ff5370
color2  #89ddff
color3  #f9e2af
color4  #4ade80
color5  #f5c2e7
color6  #c792ea
color7  #cdd6f4

color8  #585b70
color9  #ff5370
color10 #89ddff
color11 #f9e2af
color12 #4ade80
color13 #f5c2e7
color14 #c792ea
color15 #ffffff


include colors-matugen.conf
