#!/bin/sh
if status is-interactive
  set fish_greeting "Welcome to the Batcave, Master Wayne. How can I assist you today?"

	# general
	alias die="sudo shutdown -h now"
	alias cp='cp -iv'
	alias mv='mv -iv' 
	alias wget='wget -c'
	alias rm='rm -v'
	alias yeet='rm -rf'
  alias yeeet='sudo rm -rf'
	alias mkdir='mkdir -pv'
	alias ls='ls -hN --color=auto --group-directories-first'
	alias lsa='ls -a'
  alias lsl='ls -l'
  alias lsla='lsl -a'
	alias ls-storage="du -hsx -- * | sort -rh | head -10"
	alias compress='tar -czvf'
	alias extract='tar -xzvf'
  alias update-grub='sudo update-grub'
  alias x='startx'
	
  # alternatives
	alias v='nvim'
	alias vim='v'
	alias cat='bat'
	alias nano='v'
  alias emacs='v'
  alias s='sudo'
  alias se='sudo -E'
  alias vv='se nvim'
  alias lspcifzf="lspci | fzf --preview-window='top:50%:nowrap' --preview=\"echo {} | grep -o '[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]\.[0-9a-zA-Z]' | xargs -I[] lspci -k -s [] | grep -z --color=always -e '[0-9a-zA-Z][0-9a-zA-Z]:[0-9a-zA-Z][0-9a-zA-Z]\.[0-9a-zA-Z]'\""
  alias ipsbs="pacman -Qi | awk '/^Name/ {name=$3} /^Installed Size/ {print $4 $5, name}' | sort -hr | less"

	# utilities
	alias myip='curl ipinfo.io/ip'

	alias i='paru -S'
  alias aa='paru'
  alias update='paru'
	alias remove='paru -R'
  alias removeall='paru -Rcsn'
	alias search='paru'
		
	# youtube-dl
	alias get-audio='youtube-dl --extract-audio -f bestaudio '
	alias get-video='youtube-dl -f bestvideo+bestaudio '
	
	# pacman
	alias pac-unlock='sudo rm /var/lib/pacman/db.lck'
	alias pac-clean='sudo pacman -Rns (pacman -Qtdq)'
	
	# paths
  alias fishc="cd ~/.config/fish && nvim config.fish"
  alias hyprc="nvim ~/.config/hypr/hyprland.conf"
  alias codef='cd ~/stuff/code/'
  alias sc='nvim ~/.config/sxhkd/sxhkdrc'

	# funny
	alias reyeet='sudo reboot'
	alias obey='sudo'
	alias obey_as_me='sudo -E'
	alias say='yes'
	alias weather='curl wttr.in'
	alias toottoot='sl'
  alias sl='sl -100wdae'
	alias yeetermeter='btop'
	alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'
  alias where="pwd"

#   jump shell fish | source
#
# The following lines are autogenerated:
function __jump_add --on-variable PWD
  status --is-command-substitution; and return
  jump chdir
end

function __jump_hint
  set -l term (string replace -r '^j ' '' -- (commandline -cp))
  jump hint "$term"
end

function j
  set -l dir (jump cd "$argv")
  test -d "$dir"; and cd "$dir"
end

complete --command j --exclusive --arguments '(__jump_hint)'

end

set -Ux nvm_default_version 22.14.0
